version: '3.4'

networks:
  dev:
    driver: bridge

services:
  webapi:
    image: docker.io/library/dotnetdockerpostgre
    depends_on:
      - "appdb"
    container_name: dotnetdockerpostgre-demo
    ports:
      - "8088:80"
    build: 
      context: .
      dockerfile: Dockerfile
    environment: # Em tese não deveriamos migrar informações como as que estão abaixo, porém, por ser um aplicação exemplo, irei fazer isso para facilitar futuras consultas :)
      - ConnectionStringDefault__DefaultConnection=User ID=postgres;Password=postgres;Server=appdb;Port=5432;Database=DemoDb;IntegratedSecurity=true;Pooling=true
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  
  appdb:
    image: postgres:latest
    container_name: appdb    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DemoDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data: